"""
Pydantic schemas for chat session endpoints.
"""
from typing import List, Optional, Any, Annotated
from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field, BeforeValidator


def uuid_to_str(v: Any) -> str:
    """Convert UUID to string."""
    if isinstance(v, UUID):
        return str(v)
    return str(v)


class ChatSessionCreate(BaseModel):
    """Schema for creating a new chat session."""

    case_id: str = Field(..., description="Case ID")
    title: Optional[str] = Field(None, description="Optional session title")

    model_config = {"str_strip_whitespace": True}


class ChatMessageCreate(BaseModel):
    """Schema for creating a new chat message (Q&A exchange)."""

    question: str = Field(..., min_length=5, description="User's question")
    # Note: answer, confidence, and sources are generated by the backend


class ChatMessageResponse(BaseModel):
    """Schema for a single chat message."""

    id: Annotated[str, BeforeValidator(uuid_to_str)]
    chat_session_id: Annotated[str, BeforeValidator(uuid_to_str)]
    question: str
    answer: str
    confidence: float
    sources: Optional[List[dict]] = None
    created_at: datetime

    model_config = {"from_attributes": True}


class ChatSessionResponse(BaseModel):
    """Schema for chat session with messages."""

    id: Annotated[str, BeforeValidator(uuid_to_str)]
    case_id: Annotated[str, BeforeValidator(uuid_to_str)]
    user_id: int
    title: Optional[str] = None
    message_count: int = 0  # Number of messages in this session
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class ChatSessionDetailResponse(BaseModel):
    """Schema for chat session with full message history."""

    id: Annotated[str, BeforeValidator(uuid_to_str)]
    case_id: Annotated[str, BeforeValidator(uuid_to_str)]
    user_id: int
    title: Optional[str] = None
    messages: List[ChatMessageResponse] = []
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class ChatSessionListResponse(BaseModel):
    """Schema for paginated chat session list response."""

    data: List[ChatSessionResponse]
    page: int
    per_page: int
    total: int
    next_page: Optional[int] = None
