'use client';

/**
 * Token Usage Dashboard Page
 *
 * Displays user's token usage and estimated costs.
 * - Last 30 days summary
 * - Breakdown by usage type (embeddings, LLM generation, Q&A)
 * - Top cases by cost
 */

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { usageAPI, UsageDashboard } from '@/lib/api/usage';
import { AppLayout } from '@/components/layout/AppLayout';

export default function UsagePage() {
  const router = useRouter();
  const [dashboard, setDashboard] = useState<UsageDashboard | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadDashboard();
  }, []);

  const loadDashboard = async () => {
    try {
      setLoading(true);
      const data = await usageAPI.getUsageDashboard();
      setDashboard(data);
      setError(null);
    } catch (err: any) {
      // Handle authentication errors by redirecting to login
      if (err.status === 401) {
        router.push('/login?redirect=/usage');
        return;
      }
      setError(err.message || err.response?.data?.detail || 'Failed to load usage dashboard');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <AppLayout>
        <div className="flex items-center justify-center min-h-[60vh]">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
            <p className="text-muted-foreground">Loading usage data...</p>
          </div>
        </div>
      </AppLayout>
    );
  }

  if (error) {
    return (
      <AppLayout>
        <div className="bg-destructive/10 text-destructive border border-destructive/20 rounded-lg p-4">
          <h3 className="font-semibold mb-2">Error Loading Usage Data</h3>
          <p>{error}</p>
        </div>
      </AppLayout>
    );
  }

  if (!dashboard) {
    return null;
  }

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
      maximumFractionDigits: 6,
    }).format(amount);
  };

  const formatNumber = (num: number) => {
    return new Intl.NumberFormat('en-US').format(num);
  };

  const getUsageTypeLabel = (type: string) => {
    const labels: Record<string, string> = {
      embedding: 'Document Embeddings',
      llm_generation: 'Draft Generation',
      llm_qa: 'Q&A / Research',
      ocr: 'OCR Processing',
    };
    return labels[type] || type;
  };

  return (
    <AppLayout>
      <div>
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-foreground mb-2">Token Usage & Costs</h1>
          <p className="text-muted-foreground">
            Last 30 days • Updated in real-time
          </p>
        </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <div className="bg-card border border-border rounded-lg p-6">
          <p className="text-sm text-muted-foreground mb-1">Total Cost</p>
          <p className="text-3xl font-bold text-foreground">
            {formatCurrency(dashboard.summary.total_cost_usd)}
          </p>
          <p className="text-xs text-muted-foreground mt-2">
            {formatNumber(dashboard.summary.total_tokens)} total tokens
          </p>
        </div>

        <div className="bg-card border border-border rounded-lg p-6">
          <p className="text-sm text-muted-foreground mb-1">API Requests</p>
          <p className="text-3xl font-bold text-foreground">
            {formatNumber(dashboard.summary.request_count)}
          </p>
          <p className="text-xs text-muted-foreground mt-2">
            Across all operations
          </p>
        </div>

        <div className="bg-card border border-border rounded-lg p-6">
          <p className="text-sm text-muted-foreground mb-1">Input Tokens</p>
          <p className="text-3xl font-bold text-foreground">
            {formatNumber(dashboard.summary.total_input_tokens)}
          </p>
          <p className="text-xs text-muted-foreground mt-2">
            Sent to AI models
          </p>
        </div>

        <div className="bg-card border border-border rounded-lg p-6">
          <p className="text-sm text-muted-foreground mb-1">Output Tokens</p>
          <p className="text-3xl font-bold text-foreground">
            {formatNumber(dashboard.summary.total_output_tokens)}
          </p>
          <p className="text-xs text-muted-foreground mt-2">
            Generated by AI
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Usage by Type */}
        <div className="bg-card border border-border rounded-lg p-6">
          <h2 className="text-xl font-semibold text-foreground mb-4">Usage Breakdown</h2>
          <div className="space-y-4">
            {dashboard.by_type.length === 0 && (
              <p className="text-muted-foreground text-sm">No usage data yet</p>
            )}
            {dashboard.by_type.map((item) => {
              const percentage = dashboard.summary.total_cost_usd > 0
                ? (item.total_cost_usd / dashboard.summary.total_cost_usd) * 100
                : 0;

              return (
                <div key={item.usage_type} className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-foreground">
                      {getUsageTypeLabel(item.usage_type)}
                    </span>
                    <span className="text-sm font-semibold text-foreground">
                      {formatCurrency(item.total_cost_usd)}
                    </span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="flex-1 bg-muted rounded-full h-2 overflow-hidden">
                      <div
                        className="bg-primary h-full transition-all"
                        style={{ width: `${percentage}%` }}
                      ></div>
                    </div>
                    <span className="text-xs text-muted-foreground w-12 text-right">
                      {percentage.toFixed(1)}%
                    </span>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    {formatNumber(item.total_tokens)} tokens • {formatNumber(item.request_count)} requests
                  </p>
                </div>
              );
            })}
          </div>
        </div>

        {/* Top Cases by Cost */}
        <div className="bg-card border border-border rounded-lg p-6">
          <h2 className="text-xl font-semibold text-foreground mb-4">Top Cases by Cost</h2>
          <div className="space-y-3">
            {dashboard.top_cases.length === 0 && (
              <p className="text-muted-foreground text-sm">No cases yet</p>
            )}
            {dashboard.top_cases.map((item, index) => (
              <div
                key={item.case_id}
                className="flex items-center justify-between p-3 bg-accent/50 rounded-lg hover:bg-accent transition-colors"
              >
                <div className="flex items-center gap-3">
                  <div className="h-8 w-8 rounded-full bg-primary/10 flex items-center justify-center border border-primary/20">
                    <span className="text-sm font-semibold text-primary">
                      {index + 1}
                    </span>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-foreground truncate max-w-[200px]">
                      Case {item.case_id.slice(0, 8)}
                    </p>
                    <p className="text-xs text-muted-foreground">
                      {formatNumber(item.total_tokens)} tokens
                    </p>
                  </div>
                </div>
                <p className="text-sm font-semibold text-foreground">
                  {formatCurrency(item.total_cost_usd)}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Info Footer */}
      <div className="mt-8 bg-muted/30 border border-border rounded-lg p-4">
        <p className="text-sm text-muted-foreground">
          <strong>Note:</strong> Costs are estimates based on current API pricing (OpenAI, Anthropic).
          Actual billing may vary. Token usage is tracked in real-time across all AI operations including
          document processing, Q&A, and draft generation.
        </p>
      </div>
      </div>
    </AppLayout>
  );
}
